services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
  # volumes:
  #   - postgres_data:/var/lib/postgresql/data

  # web-app:
  #   build:
  #     context: ./web
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./web:/app
  #     - /app/node_modules
  #   command: yarn dev
  #   depends_on:
  #     - backend

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '4000:4000'
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   command: ./start.sh
  #   depends_on:
  #     - database

volumes:
  postgres_data:
